### DISCUSSION TITLE
Inquiry re how to transfer ownership of objects

### DISCUSSION THREAD

**Discussion by cyrdjet** [Titan-Systems/titan#154] [Q&A] [answered]
I have been using Titan Core for the past few days, testing its use in re-permissioning a cloned database within my Snowflake environment. One privilege I cannot apply is OWNERSHIP but I'm hoping it's just that I've missed something. Any direction on how to do so would be appreciated. Below is what I tried to implement but received the error "raise ValueError("Grant does not support OWNERSHIP privilege")
ValueError: Grant does not support OWNERSHIP privilege". 

grants:
- priv: OWNERSHIP
  on_database: MY_DATABASE
  to: MY_DATABASE_ADMIN

**Comment by teej** [comment, marked as answer]
Ownership is handled on the resource itself.

```
databases:
  - name: MY_DATABASE
    owner: MY_DATABASE_ADMIN
    ... other database attributes ...
```

If you haven't already, try using the CLI export tool. Try:

```
titan export --resources=database --out=databases.yml
```
