### DISCUSSION TITLE
Feature Idea: Directives

### DISCUSSION THREAD

**Discussion by titan-teej** [Titan-Systems/titan#52] [Ideas]
Titan Core should have a way to automate certain types of Snowflake best practices without the need to write a bunch of config for it. The example I had in mind was "custom roles should always be granted to SYSADMIN". There are plenty more, probably dozens.

How this would work: the YAML spec adds a `config` block. This config block has a section for each resource type.

Resource configs can have 2 types of entries: `field_defaults`, which sets a default for all resources of that type in the file, and `provisioners` that create new resources dynamically.

```yml
# blueprint.yml

roles:
  - name: loader
  - name: transformer
  - name: reporter

warehouses:
  - name: loading
    warehouse_size: XSMALL
    auto_resume: true

config:
  roles:
    provisioners:
      - grant_to_sysadmin: true
  warehouses:
    field_defaults:
      - auto_suspend: 60
```

**Comment by titan-teej** [comment]
Tags would benefit the most. Having to write tags config for 100s of different resources sucks. So instead of defining a zillion tags, you could do this:

```yaml
config:
  tags:
    provisioners:
      - name: auto_tag
        tag:
          cost_center: finance
```
