### ISSUE TITLE
Unable to use vars in database parameter for database_roles

### ISSUE THREAD

**Issue by toadies** [Titan-Systems/titan#178]
Trying to use vars for my database on the database_roles.

```
database_roles:
  - name: "{{ var.database }}_{{ var.schema }}_FULL_AR"
    database: "{{ var.database }}"
    owner: USERADMIN
```
error
```
venv/lib/python3.10/site-packages/titan/blueprint.py", line 456, in _merge_pointers
    if resource_id in namespace:
TypeError: unhashable type: 'VarString'
```
