### ISSUE TITLE
Ability to nest tables/views/etc under their parent schema or database config

### ISSUE THREAD

**Issue by GClunies** [Titan-Systems/titan#179]
I'd like the ability to nest tables/views/etc under their parent database and/or schema config. Something like this.
```yaml
# test_db.yml

databases:
  - name: test_db
    schemas:
      - name: test_schema
        tables:
          - name: test_table
            columns:
              - name: col1
                data_type: string
              - name: col2
                data_type: integer
                
          - name: test_table_2
             columns:
              - name: col1
                data_type: boolean
              - name: col2
                data_type: number
                 
        views:
          - name: test_view
            columns:
              - name: col1
                data_type: string
              - name: col2
                data_type: integer
```

I am not sure how far you want to extend this ... maybe the same would be possible for anything that is defined at the schema level?
<img width="310" alt="image" src="https://github.com/user-attachments/assets/e57161a5-12a9-4fc5-a5fa-83b820e561f8" />
