### ISSUE TITLE
[FEATURE] ability to set a masking policy on a tag

### ISSUE THREAD

**Issue by d-ohare** [Titan-Systems/titan#180]
With the recent release of masking policies as supported resources, I would like the ability to set masking policies on the tag configs. 
yml example:
```
tags:
- name: COST
  allowed_values: ['true']
  comment: Tag for cost related data.
  owner: ACCOUNTADMIN
  masking_policy:
    name: COST_POLICY
```
    
Titan would run: 
```
 alter tag cost set
    masking policy cost_policy
```
    
This would help teams who leverage Snowflake's tag based masking policies to keep even more configuration within Titan. 
Snowflake docs:
[](https://docs.snowflake.com/en/user-guide/tag-based-masking-policies)
