### ISSUE TITLE
[BUG] Doublequotes being injected when creating a new user using yaml syntax

### ISSUE THREAD

**Issue by jessanmen1** [Titan-Systems/titan#209]
_Disclaimer: I am unsure if this is a Titan bug or if I am doing something wrong. Feel free to close it's unrelated to Titan_

# Context
We are using the yaml setup to create new users in our org. Something like:
```
- name: TOMAS
  default_role: DEFAULT_ROLE
  default_warehouse: DEFAULT_WH
  disabled: false
  email: tomas@company.com
  login_name: TOMAS@COMPANY.COM
  must_change_password: false
  owner: A_OWNER
  roles:
      - some_role
```

After the Titan plan had been applied, we let the users know, and they reported that they couldn't access Snowflake. After investigation, we found out that there were double quotes in the `login_name` like this:

![Image](https://github.com/user-attachments/assets/0761b159-c7cb-4249-a230-0561776e2f9d)

Any idea of what's going on here?

Thanks in advance!
