### ISSUE TITLE
issue Using Stages in titan.yml / didn't see docs

### ISSUE THREAD

**Issue by dexhorthy** [Titan-Systems/titan#56]
might be a weird edge case, but 

```
stages:
  - name: BUNDLE
    database: METALYTICS_APP_PKG_DB
    schema: NATIVE_APP
    owner: APP_PACKAGER_ROLE
    type: internal
```

this works for create, but on subsequent runs titan tries to run the following, which fails w/ error:

```
ALTER STAGE METALYTICS_APP_PKG_DB.NATIVE_APP.BUNDLE UNSET DIRECTORY
```

and trying a few different incantations

```diff
stages:
  - name: BUNDLE
    database: METALYTICS_APP_PKG_DB
    schema: NATIVE_APP
    owner: APP_PACKAGER_ROLE
    type: internal
+   directory: enable
```

```diff
+   directory:
+     enable: true
```

```diff
+   directory:
+     enable: "true"
```

generates weird/invalid sql like 

```
ALTER STAGE <stage_name> SET DIRECTORY = {'enable': True};
```

according to copilot the right syntax is something like

```
ALTER STAGE <stage_name> SET DIRECTORY = (ENABLE = TRUE);
```

#### workaround

If you drop the stage and then re-create it with

```
stages:
  - name: BUNDLE
    database: METALYTICS_APP_PKG_DB
    schema: NATIVE_APP
    owner: APP_PACKAGER_ROLE
    type: internal
    directory:
      enable: true
```
then things seem to work going forward
