### ISSUE TITLE
User Creation double-quotes names with `@` symbol

### ISSUE THREAD

**Issue by dexhorthy** [Titan-Systems/titan#68]
```yaml
# titan.yml

users:
  - name: matt@metalytics.dev
```

This creates the user with extra quotes, 

| Name | Created | Login_name |
|-------| --------| ------------|

![image](https://github.com/Titan-Systems/titan/assets/3730605/09158681-f0e9-43c2-820a-e0439b8f9309)

and in order to log in as this user, need to do something like

```
SNOWSQL_USER='"matt@metalytics.dev"'
```
